### ISSUE TITLE
StringField._regex and Field._regex are too restrictive

### ISSUE THREAD

**Issue by micro-belgium-application** [mhemeryck/pycoda#44]
I have issue with multiples coda that don't match those regex.

I think you should add characters like \+:éè­  or even allow all characters.

**Comment by mhemeryck** [comment]
Hey, I only rarely check this repo nowadays, so sorry for the late reply.

Thanks for reaching out; I've noticed a similar issue when testing on bigger batches of CODA files.

I will look into loosening up the restrictions (I actually think indeed that for the string fields, we should just be able to allow everything).
